# 사이킷런 내장 예제 데이터

머신러닝은 데이터기반임
데이터를 잘 다룰수있어야..함 ! 

### 붓꽃 데이터 세트 기반의 ML 분류 예측 수행 프로세스 

In [2]:
# 그림06 (93page 앞부분은 넘파이 판다스라 빼셨다고 함)

테스트데이터값에는 피쳐만 주고 예측 

In [ ]:
사이킷런 기반 프레임워크 : Estimator와 fit()/predit()
    
사이킷런에서 제공하는 메소드
- fit() : ML 모델 학습
- predict() : 학습된 모델의 예측

지도학습의 분류와 회귀에서 fit()과 predcit()만 사용해서 간단하게 학습과 예측 결과를 반환 해줌 
- 분류 알고리즘을 구현한 클래스 : ~ Classifier
- 회귀 알고리즘을 구현한 클래스 : ~ Regressor 
    
Estimator 클래스 : Classifier + Regressor 클래스
- 지도학습의 모든 알고리즘을 구현한 클래스를 통칭
- fit()과 predict() 내부에서 구현


In [ ]:
# 그림07

In [3]:
### 사이킷런의 내장 데이터 세트 형태 


사이킷런의 내장 데이터 세트 형태
- key 구성 : data, target, target_names, feature_names, DESCR
- data : 피처 데이터 세트 (ndarry)
- target : 분류(레이블 값)/회귀(숫자 결과값 데이터 세트) (ndarry)
- target_names : 개별 레이블 이름 (ndarry 또는 list)
- feature_names : 피처 이름 (ndarry 또는 list)
- DESCR : 데이터 세트 설명, 각 피처 설명 (string)


머신러닝 모델을 구축하는 주요 프로세스  
(1) 피처의 가공, 변경, 추출을 수행하는 피처 처리  
(2) ML 알고리즘 학습/예측 수행  
(3) 모델 평가  
- (1)(2)(3) 단계를 반복적으로 수행 

In [4]:
### 붓꽃 데이터 세트 구성 

In [5]:
# 그림08

타겟=레이블=결정값=정답

In [7]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [8]:
# sklearn.utile.Bunch
# 파이썬의 딕셔너리 형태와 유사함 : key와 value로 이루어짐

In [9]:
# 키 값만 출력
keys=iris_data.keys()
print('붓꽃 데이터 세트의 key : ',keys)

붓꽃 데이터 세트의 key :  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [10]:
# data 확인
print('data의 type : ', type(iris_data.data))
print('data의 shape : ', iris_data.data.shape)
print(iris_data['data'])


data의 type :  <class 'numpy.ndarray'>
data의 shape :  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3

In [12]:
# target 확인
print('target의 type : ', type(iris_data.target))
print('target의 shape : ', iris_data.target.shape)
print(iris_data.target)
# 각각의 값이 0인지 1인지 1차원값

target의 type :  <class 'numpy.ndarray'>
target의 shape :  (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
# 타깃 이름 학인 
# target 확인
print('target_names의 type : ', type(iris_data.target))
print('target_names의 크기 : ', len(iris_data.target.names))
print(iris_data.target_names)
# 각각의 값이 0인지 1인지 1차원값

In [14]:
# 피처 이름 확인 

In [16]:
# 전체 데이터 세트 설명 : 각 피처 설명 (string으로 출력할것임)